### PR TITLE
Feature/Filter matchups by city and sport

### PR DESCRIPTION
**Pull request by topherbentz**
- Add text inputs on homepage to filter city and sport
- Add call to server filter matchups based on city and sport inputs
- Pass functions from app.js through props to matchupCard.js
- Add dependency on querystring

### CODE REVIEW

**Comment by JCraigWasTaken** [comment]
I'll merge if you can confirm that we escape the input strings.

**Comment by JCraigWasTaken** [comment]
Like, because otherwise we can have some fun SQL injection going on.

**Comment by JCraigWasTaken** [comment]
Front-end looks safe, going to find a way to sanitize back-end inputs on train tn

**Comment by topherbentz** [comment]
Good point about sanitization, I can handle that. I found some good resources on it.

**Comment by topherbentz** [comment]
Added mongo-sanitize and used it on all parameters to avoid injection attacks. We should use this on any parameters for queries to the db moving forward.

**Pull request merged**
